<?php
// add the current day and month at the end of variables to reduce duplicate chance
// Miscellaneous
$wtgcsv_phpversionwarning_0109 = __('The plugin detected an older php version than the minimum requirement which is '.WTG_CSV_PHPVERSIONMINIMUM.'. Wordpress itself also operates better with a later version of php than you are using. Most features will work fine but some important ones will not.');
// wtgcsv_main_install
$wtgcsv_install_intro_2509 = __('All you need to do to begin using the plugin is click on the install button below.');
$wtgcsv_install_help_2509 = __('Press the install button to begin using the plugin. More information is provided however so you can learn and understand exactly what my plugin does to your blog. When this plugin is activated, it does not make any changes to your Wordpress database or file system. No records are added to the Wordpress options table and no new tables are created in the database. The only thing done prior to actual installation is activation by Wordpress, the step you take on the plugin screen. The plugins other screens are hidden and until you press the install button.');
$wtgcsv_reinstall_intro_0110 = __('Re-install all or selected parts of the plugin.');
$wtgcsv_reinstall_help_0110 = __('Select the specific items you would like to re-install. In most cases you would select them all for a complete fresh install but in some cases you might want to keep existing data/settings to save time configuring your new installation of the plugin.');
$wtgcsv_uninstall_intro_0210 = __('Delete the plugins settings, uploaded files and database tables');
$wtgcsv_uninstall_help_0210 = __('This tool allows you to delete existing records, files and database tables so that there is no longer a trace of the installation. Settings are stored in the Wordpress options table and will be removed from there. You can leave some elements of the installation in your blog for using in future or possibly to support another plugin. Just ignore this ability if your not sure what it means or you want the most simple way to remove the plugin. Just remember if you do this and then attempt to install the blog in future you may get error type messages simply letting you know something was not installed but really indicating that it already exists.');
$wtgcsv_installlog_intro_0510 = __('Here you can view installation status related entries to the general log file');
$wtgcsv_installlog_help_0510 = __('Any actions related to the installation status of '.WTG_CSV_PLUGINTITLE.' will be logged in the General log file. The plugin filters log entries related to install, re-insall or un-install changes. This is mainly for troubleshooting but in some cases we can offer the ability to change your installation without logging into your blog. The log entries are imported to review such changes.');
$wtgcsv_installstatus_intro_0510 = __('View the status of option records and database tables');
$wtgcsv_installstatus_help_0510 = __('Wordpress allows us to store settings/options in the options table. Multiple option values can be held in a single record. This panel allows us to quickly view the status of individual option records and any database tables your current configuration requires.');
$wtgcsv_logfilestatus_intro_0710 = __('Check what files exist or not and the log recording status.');
$wtgcsv_logfilestatus_help_0710 = __('Log files are not required for the plugin to operate but they can help you monitor your projects activity or for troubleshooting should your project settings not be as you need them yet. '.WTG_CSV_PLUGINTITLE.' has multiple log files, each containing rows of information from different aspects of the plugin. You do not need to have all of them active or any of them. Some may not mean a lot to you especially if your not a developer i.e. the sql log file. These files are great for sending by email when requesting support.');
$wtgcsv_install_missingparts_0810 = __('A required part of the plugins installation is missing. Have you possibly manually deleted tables or option records from the database? You can use the main re-install feature if it is alright to lose any other existing installed parts or go to the Install Status page to install individual parts.');
$wtgcsv_databasetablesstatus_intro_0810 = __('The status of required tables will be displayed here.');
$wtgcsv_databasetablesstatus_help_0810 = __('The plugin may not always require database tables so none may show here. It can depend on various aspects such as the edition you have, your installation configuration or specific features you have initiated. We try not to create database tables until they are needed.');
$wtgcsv_nointernet_1010 = __('An internet connection could not be detected and is required. '.WTG_CSV_PLUGINTITLE.' loads files from jQuery.com and Google. Without the files JavaScript, jQuery and Ajax will not work properly. Please note that this test is done by attempting to connect to Google.com due to reliable but should it ever go offline, it will cause this message.');
?>